@extends('admin.layout.main')

@section('content')
<div class="layout-px-spacing">

    <div class="page-header">
        <div class="page-title">
            <h3>All Quotation</h3>
        </div>
        
        <div class="toggle-switch">
            <div>
                {{-- <label for="">Search</label>
                <input type="text" class="form-control" placeholder="Notification" aria-label="notification"
                    aria-describedby="basic-addon2">
                <span toggle="#confirm_pass" class="fas fa-search text-grey searchicon"></span> --}}
    
            </div>
            <div class="pl-3">
                <label for="#buyersearch">Buyer</label>
                <select class="w-100 p-lg-2 border-muted form-control" id="buyersearch">
                    <option value="">Choose Anyone</option>
                    @foreach ($users as $user)
                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                    @endforeach
                </select>
            </div>
        
            <div class="pl-3">
                <label for="#statussearch"> Status</label>
                <select class="w-100 p-lg-2 border-muted form-control" id="statussearch">
                    <option value="">Choose Anyone</option>
                    <option value="1">Active</option>
                    <option value="2">Inactive</option>
    
                </select>
            </div>
       
    
    
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <p class="text-left">Showing 290 Quotations</p>
                <table class="table mb-4" style="margin: 0 !important;
                border: none !important;">
                    <thead class="">
                        <tr>
                            <th class="">Quotations Details </th>
                            <th class="" width="200px">Buyer Name</th>
                            <th class="" width="200px">Buyer Activity</th>
                            <th>Status </th>
                            <th>Controls</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white">
                        @php
                            $i = 1;
                        @endphp
                        @foreach ($quotations as $quotation)
                        
                            <tr>
                                <td class="text-left"><strong>{{ $quotation->catname }}</strong> <br>
                                    {{ $quotation->record_count }} Products <br>Generated by {{ $quotation->email }} at
                                    {{ $quotation->created_at ?? '' }}</td>
                                <td>{{ $quotation->buyer_name }} </td>
                                <td></td>
                                <td class=""><span class=" shadow-none badge outline-badge-primary">
                                        @if ($quotation->status == 0)
                                         Priview Pending
                                        @elseif($quotation->status == 1)
                                        Canceled
                                        @elseif($quotation->status == 2)
                                        Sending Buyer
                                        @elseif($quotation->status == 3)
                                        Buyer Resending
                                        @else
                                        Completed
                                        @endif
                                    </span>
                                </td>
        
                                <td>
                                    <div class="justify-content-between d-flex">
                                        <span class="p-1 bg-light-dark text-dark"><i class="fa-solid fa-user-shield"></i></span>
                                        <a href="{{route('user.sendinvoice',['token'=>$quotation->token,'catid'=>$quotation->catalog_id])}}"
                                            class="p-1 bg-light-dark text-dark linknext" data-id="{{ $i }}"
                                            id="linknext{{ $i }}">{{route('user.sendinvoice',['token'=>$quotation->token,'catid'=>$quotation->catalog_id])}}</a>
                                        <button
                                            class="badge border-primary border-width-1px ml-1 mr-1 p-1 text-primary copylinkbtn"
                                            id="copylinkbtn{{ $i }}" data-id="{{ $i }}">Copy
                                            Link</button>
    
                                        <a href="{{ route('quotation.view', [
                                            'catalog_id' => $quotation->catalog_id,
                                            'company_id' => $quotation->company_id,
                                            'buyer_id' => $quotation->buyer_id,
                                            'userid' => $quotation->userid,
                                        ]) }}"
                                            class="p-1 bg-light-dark text-dark showqutation" >Preview</a> <span
                                            class="p-1 bg-light-dark text-dark"><i
                                                class="fa-solid fa-file-arrow-down"></i></span> <span
                                            class="p-1 bg-light-dark text-dark"><i
                                                class="fa-solid fa-ellipsis-vertical"></i></span>
                                    </div>
                                </td>
                            </tr>
                            @php
                                $i++;
                            @endphp
                        @endforeach
        
                    </tbody>
                </table>
            </div>
        </div>
    </div>



</div>
@endsection
@section('script')
@include('admin.pages.quotation.script')


@endsection
