<div class="page-header">


    <div class="toggle-switch">
        <div>
            <label for="">Search</label>
            <input type="text" class="form-control" placeholder="Notification" aria-label="notification"
                aria-describedby="basic-addon2">
            <span toggle="#confirm_pass" class="fas fa-search text-grey searchicon"></span>

        </div>
        <div class="pl-3">
            <label for="#buyersearch">Buyer</label>
            <select class="w-100 p-lg-2 border-muted form-control" id="buyersearch">
                <option value="">Choose Anyone</option>
                @foreach ($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="pl-3">
            <label for="#usersearch">User</label>
            <select class="w-100 p-lg-2 border-muted form-control"  id="usersearch">
                <option value="">Choose Anyone</option>
                @foreach ($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach

            </select>
        </div>
        <div class="pl-3">
            <label for="#statussearch"> Status</label>
            <select class="w-100 p-lg-2 border-muted form-control" id="statussearch">
                <option value="">Choose Anyone</option>
                <option value="1">Active</option>
                <option value="2">Inactive</option>

            </select>
        </div>
        <div class="pl-3">
            <label for="#createonsearch">Created On</label>
            <select class="w-100 p-lg-2 border-muted form-control" id="createonsearch">
                <option value="">Choose Anyone</option>
                <option value="">Mustard</option>
                <option value="">Ketchup</option>
                <option value="">Relish</option>
            </select>
        </div>


    </div>
</div>
<div class="row layout-top-spacing">
   <div class="col-md-12">
    <div class="table-responsive">
        <p class="text-left">Showing 290 catalogue</p>
        <table class="table" style="width: 100% !important;
        border: none !important;" >
            <thead >
                <tr>
                    <th class="">Catalogue Details </th>
                    <th class="" width="200px">Buyer Name</th>
                    <th class="" width="200px">Buyer Activity</th>
                    <th>Status </th>
                    <th>Controls</th>
                </tr>
            </thead>
            <tbody class="bg-white">
                @php
                    $i = 1;
                @endphp
                @foreach ($catalogues as $catalogue)
                    <tr>
                        <td class="text-center"><strong>{{ $catalogue->catname }}</strong> &nbsp;&nbsp;
                            {{ $catalogue->record_count }} Products <br>Generated by {{ $catalogue->email }} 
                            </td>
                        <td>{{ $catalogue->buyer_name }} </td>
                        <td></td>
                        <td class=""><span class=" shadow-none badge outline-badge-primary p-2">
                                @if ($catalogue->status == 1)
                                    Active
                                @else
                                    Inactive
                                @endif
                            </span>
                        </td>

                        <td>
                            <div class="justify-content-between d-flex">
                                <span class="p-2 bg-light-dark text-dark"><i class="fa-solid fa-user-shield"></i></span>
                                <a href="{{ route('user.viewcatalogue', $catalogue->securitycode) }}"
                                    class="p-2 bg-light-dark text-dark linknext" data-id="{{ $i }}"
                                    id="linknext{{ $i }}">{{ route('user.viewcatalogue', $catalogue->securitycode) }}</a>
                                <button
                                    class="badge border-primary border-width-1px ml-1 mr-1 p-2 text-primary copylinkbtn"
                                    id="copylinkbtn{{ $i }}" data-id="{{ $i }}">Copy
                                    Link</button>
                                <a href="{{ route('catalogue.allproduct', ['catid' => $catalogue->catalog_id, 'token' => $catalogue->securitycode,'userid'=>$catalogue->userid]) }}
                                    "
                                    class="p-2 bg-light-dark text-dark showqutation" >Preview</a> <span
                                    class="p-2 bg-light-dark text-dark pdfGenerate" data-id="{{$catalogue->catalog_id}}" data-token="{{$catalogue->securitycode}}"><i
                                        class="fa-solid fa-file-arrow-down"></i></span> <span
                                    class="p-2 bg-light-dark text-dark"><i
                                        class="fa-solid fa-ellipsis-vertical"></i></span>
                                       
                            </div>
                        </td>
                    </tr>
                    @php
                        $i++;
                    @endphp
                @endforeach

            </tbody>
        </table>
    </div>
   </div>
</div>
